.PHONY: help install dev frontend test coverage lint format typecheck audit migrate migration docker-up docker-down docker-logs clean

SHELL := /bin/bash

# Automatically use local virtualenv binaries if present, otherwise fallback to system PATH
VENV := $(shell if [ -d "./venv/bin" ]; then echo "./venv/bin/"; fi)

# Default target: display help menu
help: ## Show this help message
	@echo "🎵 Vinyl Crate — Developer Command Menu"
	@echo ""
	@echo "Usage: make [target]"
	@echo ""
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

# -------------------------------------------------------------
# Setup & Installation
# -------------------------------------------------------------
install: ## Install both backend and frontend dependencies
	$(VENV)pip install --upgrade pip
	$(VENV)pip install -e ".[dev]"
	cd frontend && npm install

# -------------------------------------------------------------
# Local Development
# -------------------------------------------------------------
dev: ## Start FastAPI backend server with hot-reloading
	$(VENV)uvicorn main:app --reload --host 0.0.0.0 --port 8000

frontend: ## Start React frontend Vite dev server
	cd frontend && npm run dev

# -------------------------------------------------------------
# Code Quality, Typechecking & Security
# -------------------------------------------------------------
lint: ## Check codebase for linting issues using Ruff
	$(VENV)ruff check app/ tests/

format: ## Automatically format code and fix lint issues
	$(VENV)ruff check --fix app/ tests/
	$(VENV)ruff format app/ tests/

typecheck: ## Run Mypy static type checker
	$(VENV)mypy app/

audit: ## Scan dependencies for security vulnerabilities using pip-audit
	$(VENV)pip-audit

test: ## Run full Pytest test suite
	$(VENV)pytest -v

coverage: ## Run Pytest test suite with code coverage report
	$(VENV)pytest -v --cov=app --cov-report=term-missing tests/

# -------------------------------------------------------------
# Database & Migrations
# -------------------------------------------------------------
migrate: ## Apply pending Alembic database migrations
	$(VENV)alembic upgrade head

migration: ## Generate new autogenerated migration revision (e.g. make migration msg="add genre")
	$(VENV)alembic revision --autogenerate -m "$(msg)"

# -------------------------------------------------------------
# Docker Orchestration
# -------------------------------------------------------------
docker-up: ## Build and start all services via Docker Compose
	docker compose up --build

docker-down: ## Stop all Docker Compose services
	docker compose down

docker-logs: ## View live streaming logs from Docker containers
	docker compose logs -f

# -------------------------------------------------------------
# Cleanup
# -------------------------------------------------------------
clean: ## Remove cache directories, build artifacts, and test coverage files
	find . -type d -name "__pycache__" -exec rm -rf {} +
	find . -type d -name ".pytest_cache" -exec rm -rf {} +
	find . -type d -name ".ruff_cache" -exec rm -rf {} +
	find . -type d -name ".mypy_cache" -exec rm -rf {} +
	find . -type f -name ".coverage" -delete
	rm -rf dist/ build/ *.egg-info frontend/dist/
